### ISSUE TITLE
Memory deallocation on controller dispose

### ISSUE THREAD

**Issue by miles-au** [olexale/arkit_flutter_plugin#89] opened 2020-07-08 04:37 UTC
In the example app, if I continue to open and close multiple AR screens, the amount of memory used goes up every time I open a screen. It looks like the controller's dispose function pauses the session, but if I open a new page, it appears to initialize a new controller without deallocating the last one. 

I need a similar functionality to the example app where the user can go in and out of the AR screens. Is there a workaround to this?

**Comment by olexale** [comment] 2020-07-08 10:22
Hi @miles-au ,

Yeah, it seems that we have a leak in the plugin. I'll get back to this later.

Regards,
Olexandr

**Comment by miles-au** [comment] 2020-07-08 23:37
@olexale Is there anyway I could help? If you point me in the right direction, I could maybe at least make an attempt.

Initially I was thinking that this could be solved by setting the ARSCNView to nil on dispose, but it doesn't seem like a very nice solution. It would also require turning the sceneview variable into an optional.

**Comment by James-A-White** [comment] 2020-07-09 19:20
I've also encountered this problem.  Sometimes my app crashes, sometimes it corrupts the OS of the device to the extent that we have to reboot to get it to work again.  I'm guessing that my problem is also related to a memory leak.

**Comment by olexale** [comment] 2020-07-15 07:35
@miles-au , a few weeks earlier I profiled the sample app, and for me it looked like there is a problem in the Flutter native view bridging mechanism (it's still in preview). On the other hand, there are lots of other plugins that use the same mechanism, hence most probably the problem is somewhere in the plugin's code. My next step was to go with the profiler one more time, maybe I just missed something obvious, and after that to take, for example, [google_maps_flutter](https://pub.dev/packages/google_maps_flutter) plugin and compare the initialization and destruction code.

**Comment by AlexShmukler** [comment] 2020-09-23 12:22
Hi @olexale! Facing a similar issue. If I open and close the same screen with ARKitSceneView for ~10 times the app crashes. Do you have any updates/workarounds on this? 
My flutter version is 1.17.5. Can changing the flutter version help?

**Comment by BrutalCoding** [comment] 2020-10-20 02:42
I've got the same issue here, seems like the dispose method does not dispose properly. Any updates on this issue?

**Comment by BrutalCoding** [comment] 2020-10-22 01:24
I've made a PR that fixed the issue, seems to work fine in my use cases which is opening/closing AR page several times, going to background and back and spawning a .dae node every time AR is opened.

See https://github.com/olexale/arkit_flutter_plugin/pull/112

**Comment by olexale** [comment] 2020-10-22 18:19
This should be fixed in 0.6.0. Could you please check?

**Comment by BrutalCoding** [comment] 2020-10-23 02:29
I've checked it and closed down my PR, your fix looks cleaner and more robust. This issue can be closed since the  memory leak is no longer an issue. @olexale @miles-au

**Closed** 2020-10-25 08:51 UTC
